version = 1
SPDX-PackageName = "opendatahub-content-importer"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-content-importer"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", ".dockerignore", ".env.example", ".gitmodules", "docker-compose.dcproj", "**/**.sln", "**/**.csproj", "**/**.fsproj", "**/appsettings.**", "**/Dockerfile","**/docker-compose.**", "**/**.json", "**/Properties/**.json", "**/xml/**.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
